### ISSUE TITLE
It can not work well on the latest version of Xcode:8.3.3

### ISSUE THREAD

**Issue by bolan9999** [baptistefetet/KeychainItemWrapper#1]
100% crash on [KeychainItemWrapper writeToKeychain].
 NSAssert error:"Couldn't add the Keychain Item."

**Comment by ajayd12** [comment]
You should enable Keychain Sharing in Xcode, Xcode Capabilities editor on the target settings panel to turn on Keychain Sharing.
It will help you

**Comment by bolan9999** [comment]
I have solved it. Group is incorrect. Thank you anymore
